#!/usr/apps/weave/weave-develop-cpu/bin/python3

# Package Import
try:
    import pydv.pdv
    pydv.pdv.Command().main()

# HPC Import
except ImportError:
    #import sys
    #sys.path.append("/collab/usr/gapps/pdv/bin")
    import pdv
    pdv.Command().main()
