
name: Release

on: push
# on:
#   push:
#     branches: [ master ]
#   # push:
#   #   branches: [ master, pydv-230-script-for-tag-and-prerelease ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Export version number
        run: export release_version=$(cat pydv/scripts/version.txt)
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${release_version}
      #     release_name: ${release_version}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
